### ISSUE TITLE
Support for loading from QPI NAND Flash chips?

### ISSUE THREAD

**Issue by grayxr** [newdigate/teensy-sample-flashloader#1]
Hi, I was wondering if it would be straight forward to implement an option to load samples from the SD card into QPI NAND flash chips, like the 256MB NAND chip (W25N02) that the Teensy supports.

I was interested in having more than 8MB of PSRAM to load samples from, since I'm working on a project where that limit will likely be met pretty easily with multiple samples being played at one time.

Thanks so much in advance for any consideration.

**Comment by newdigate** [comment]
are you able to use LittleFS to access the NAND? 

unfortunately the library only currently supports PSRAM writing to 0x70000000 (see [hackster.io](https://www.hackster.io/news/adding-more-ram-and-flash-to-the-teensy-4-1-89e527855502.amp) 

I could look at extending to support LittleFS but its going on the low priority because i don’t have much incentive, mostly as i don’t have any flash ic chips to test. but i think it’s a reasonable requirement and I think other people would benefit from this feature.

**Comment by grayxr** [comment]
Thanks @newdigate -- just some context, I'm currently only trying to play three ~1sec long 16bit mono samples in a sequenced drum pattern. Eventually, I'd like to support a max of 16 simultaneous ~1-to-10sec long samples at a max of 170bpm. 

When I tried using LittleFS audio objects, I noticed that the playback seemed to stutter quite a lot. This could also be the way I was copying the files from the SD card to the NAND flash though, maybe they were corrupted or something, or maybe it's the BPM clock I'm using.

But when I use the `teensy-sample-flashloader` approach, the playback is really smooth no matter how fast/slow the BPM is. But your library here is currently limited to 8-16MB PSRAM that the Teensy can have, and since I have a 256MB NAND flash, I was just hoping I could use that extra space. The NAND chip might just be too slow to read from for my use case.

**Comment by newdigate** [comment]
This approach might just be crazy enough to work your situation. and probably a top class uSD card may cope...

If you resampled your samples from 44100 to 22050 samples / sec using quadratic interpolation, and playback at half speed on the microcontroller, using quadratic interpolation, you wouldn't loose too much quality and you'd have effectively double the bandwidth. but you'd also be using more cpu.

RE: polyphony, I use this library to share voices across channels, etc. could it be useful? [teensy-polyphony
](https://github.com/newdigate/teensy-polyphony)

**Comment by grayxr** [comment]
I can try that `teensy-polyphony` library just to better manage the way the samples are playing simultaneously, but my main concern here was just wanting to store samples with longer lengths in flash somewhere, which requires more space, so as not to not stream directly from the SD card, though it seems that is how most are doing it anyway. Maybe I just need to fight through it and try and get it working.

Though, if I stick with `teensy-sample-flashloader`, and if I soldered two 8MB PSRAM chips on my Teensy to have 16MB PSRAM total, I could just try to limit the samples to ~1MB per voice and that gives me at least a ~10s mono sample length for each voice, which is fine for a really basic drum sampler I guess. Or I could limit the number of sampler voices to like 4 and then I get 4x the max sample length per voice.

**Comment by newdigate** [comment]
ideally you would play the long samples from the uSD while the more used and smaller samples read from PSRAM.

also if you have stereo samples, some you could make mono. 


And maybe you should also try different flash chips, Im guessing the bigger they are in size, the worse they perform, maybe 32 MB instead of 256 is a good place to start testing performance. LittleFS might not be the bottleneck, but I have had feedback about LittleFS performance being not-great. but I don't know if it was the Flash chip behind it that was slow. 

from [teensy-variable-playback](https://github.com/newdigate/teensy-variable-playback) for uSD card - for best performance, use SDXC UHS 30MB/sec Application Performance Class 2 (A2) class micro sd-card, or better...
